#!/bin/bash
clear

#Display CPU Temp
vcgencmd measure_temp

#Display CPU Freq
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

#Bench test1 
sysbench --test=cpu --cpu-max-prime=1000 --num-threads=4 run

#Display CPU Temp
vcgencmd measure_temp

#Display CPU Freq
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

#Longer test
sysbench --test=cpu --cpu-max-prime=50000 --num-threads=4 run

#Display temp nd freq
vcgencmd measure_temp

#Display CPU Freq
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

